/*
Generated by https://github.com/tamac-io/openapi-to-eclcloud-rb
*/
package testing

import (
	"fmt"
)

const id = "497f6eca-6276-4993-bfeb-53cbbbba6f08"

var listResponse = fmt.Sprintf(`
{
    "health_monitors": [
        {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "name": "health_monitor",
            "description": "description",
            "tags": {
                "key": "value"
            },
            "configuration_status": "ACTIVE",
            "operation_status": "COMPLETE",
            "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
            "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
            "port": 80,
            "protocol": "http",
            "interval": 5,
            "retry": 3,
            "timeout": 5,
            "path": "/health",
            "http_status_code": "200-299"
        }
    ]
}`)

var createRequest = fmt.Sprintf(`
{
    "health_monitor": {
        "name": "health_monitor",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "port": 80,
        "protocol": "http",
        "interval": 5,
        "retry": 3,
        "timeout": 5,
        "path": "/health",
        "http_status_code": "200-299",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040"
    }
}`)

var createResponse = fmt.Sprintf(`
{
    "health_monitor": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "health_monitor",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "port": null,
        "protocol": null,
        "interval": null,
        "retry": null,
        "timeout": null,
        "path": null,
        "http_status_code": null
    }
}`)

var showResponse = fmt.Sprintf(`
{
    "health_monitor": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "health_monitor",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "ACTIVE",
        "operation_status": "COMPLETE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "port": 80,
        "protocol": "http",
        "interval": 5,
        "retry": 3,
        "timeout": 5,
        "path": "/health",
        "http_status_code": "200-299",
        "current": {
            "port": 80,
            "protocol": "http",
            "interval": 5,
            "retry": 3,
            "timeout": 5,
            "path": "/health",
            "http_status_code": "200-299"
        },
        "staged": null
    }
}`)

var updateRequest = fmt.Sprintf(`
{
    "health_monitor": {
        "name": "health_monitor",
        "description": "description",
        "tags": {
            "key": "value"
        }
    }
}`)

var updateResponse = fmt.Sprintf(`
{
    "health_monitor": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "health_monitor",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "port": null,
        "protocol": null,
        "interval": null,
        "retry": null,
        "timeout": null,
        "path": null,
        "http_status_code": null
    }
}`)

var createStagedRequest = fmt.Sprintf(`
{
    "health_monitor": {
        "port": 80,
        "protocol": "http",
        "interval": 5,
        "retry": 3,
        "timeout": 5,
        "path": "/health",
        "http_status_code": "200-299"
    }
}`)

var createStagedResponse = fmt.Sprintf(`
{
    "health_monitor": {
        "port": 80,
        "protocol": "http",
        "interval": 5,
        "retry": 3,
        "timeout": 5,
        "path": "/health",
        "http_status_code": "200-299"
    }
}`)

var showStagedResponse = fmt.Sprintf(`
{
    "health_monitor": {
        "port": 80,
        "protocol": "http",
        "interval": 5,
        "retry": 3,
        "timeout": 5,
        "path": "/health",
        "http_status_code": "200-299"
    }
}`)

var updateStagedRequest = fmt.Sprintf(`
{
    "health_monitor": {
        "port": 80,
        "protocol": "http",
        "interval": 5,
        "retry": 3,
        "timeout": 5,
        "path": "/health",
        "http_status_code": "200-299"
    }
}`)

var updateStagedResponse = fmt.Sprintf(`
{
    "health_monitor": {
        "port": 80,
        "protocol": "http",
        "interval": 5,
        "retry": 3,
        "timeout": 5,
        "path": "/health",
        "http_status_code": "200-299"
    }
}`)
