/*
Generated by https://github.com/tamac-io/openapi-to-eclcloud-rb
*/
package testing

import (
	"fmt"
)

const id = "497f6eca-6276-4993-bfeb-53cbbbba6f08"

var listResponse = fmt.Sprintf(`
{
    "policies": [
        {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "name": "policy",
            "description": "description",
            "tags": {
                "key": "value"
            },
            "configuration_status": "ACTIVE",
            "operation_status": "COMPLETE",
            "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
            "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
            "algorithm": "round-robin",
            "persistence": "cookie",
            "sorry_page_url": "https://example.com/sorry",
            "source_nat": "enable",
            "certificate_id": "f57a98fe-d63e-4048-93a0-51fe163f30d7",
            "health_monitor_id": "dd7a96d6-4e66-4666-baca-a8555f0c472c",
            "listener_id": "68633f4f-f52a-402f-8572-b8173418904f",
            "default_target_group_id": "a44c4072-ed90-4b50-a33a-6b38fb10c7db",
            "tls_policy_id": "4ba79662-f2a1-41a4-a3d9-595799bbcd86"
        }
    ]
}`)

var createRequest = fmt.Sprintf(`
{
    "policy": {
        "name": "policy",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "algorithm": "round-robin",
        "persistence": "cookie",
        "sorry_page_url": "https://example.com/sorry",
        "source_nat": "enable",
        "certificate_id": "f57a98fe-d63e-4048-93a0-51fe163f30d7",
        "health_monitor_id": "dd7a96d6-4e66-4666-baca-a8555f0c472c",
        "listener_id": "68633f4f-f52a-402f-8572-b8173418904f",
        "default_target_group_id": "a44c4072-ed90-4b50-a33a-6b38fb10c7db",
        "tls_policy_id": "4ba79662-f2a1-41a4-a3d9-595799bbcd86",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040"
    }
}`)

var createResponse = fmt.Sprintf(`
{
    "policy": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "policy",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "algorithm": null,
        "persistence": null,
        "sorry_page_url": null,
        "source_nat": null,
        "certificate_id": null,
        "health_monitor_id": null,
        "listener_id": null,
        "default_target_group_id": null,
        "tls_policy_id": null
    }
}`)

var showResponse = fmt.Sprintf(`
{
    "policy": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "policy",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "ACTIVE",
        "operation_status": "COMPLETE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "algorithm": "round-robin",
        "persistence": "cookie",
        "sorry_page_url": "https://example.com/sorry",
        "source_nat": "enable",
        "certificate_id": "f57a98fe-d63e-4048-93a0-51fe163f30d7",
        "health_monitor_id": "dd7a96d6-4e66-4666-baca-a8555f0c472c",
        "listener_id": "68633f4f-f52a-402f-8572-b8173418904f",
        "default_target_group_id": "a44c4072-ed90-4b50-a33a-6b38fb10c7db",
        "tls_policy_id": "4ba79662-f2a1-41a4-a3d9-595799bbcd86",
        "current": {
            "algorithm": "round-robin",
            "persistence": "cookie",
            "sorry_page_url": "https://example.com/sorry",
            "source_nat": "enable",
            "certificate_id": "f57a98fe-d63e-4048-93a0-51fe163f30d7",
            "health_monitor_id": "dd7a96d6-4e66-4666-baca-a8555f0c472c",
            "listener_id": "68633f4f-f52a-402f-8572-b8173418904f",
            "default_target_group_id": "a44c4072-ed90-4b50-a33a-6b38fb10c7db",
            "tls_policy_id": "4ba79662-f2a1-41a4-a3d9-595799bbcd86"
        },
        "staged": null
    }
}`)

var updateRequest = fmt.Sprintf(`
{
    "policy": {
        "name": "policy",
        "description": "description",
        "tags": {
            "key": "value"
        }
    }
}`)

var updateResponse = fmt.Sprintf(`
{
    "policy": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "policy",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "algorithm": null,
        "persistence": null,
        "sorry_page_url": null,
        "source_nat": null,
        "certificate_id": null,
        "health_monitor_id": null,
        "listener_id": null,
        "default_target_group_id": null,
        "tls_policy_id": null
    }
}`)

var createStagedRequest = fmt.Sprintf(`
{
    "policy": {
        "algorithm": "round-robin",
        "persistence": "cookie",
        "sorry_page_url": "https://example.com/sorry",
        "source_nat": "enable",
        "certificate_id": "f57a98fe-d63e-4048-93a0-51fe163f30d7",
        "health_monitor_id": "dd7a96d6-4e66-4666-baca-a8555f0c472c",
        "listener_id": "68633f4f-f52a-402f-8572-b8173418904f",
        "default_target_group_id": "a44c4072-ed90-4b50-a33a-6b38fb10c7db",
        "tls_policy_id": "4ba79662-f2a1-41a4-a3d9-595799bbcd86"
    }
}`)

var createStagedResponse = fmt.Sprintf(`
{
    "policy": {
        "algorithm": "round-robin",
        "persistence": "cookie",
        "sorry_page_url": "https://example.com/sorry",
        "source_nat": "enable",
        "certificate_id": "f57a98fe-d63e-4048-93a0-51fe163f30d7",
        "health_monitor_id": "dd7a96d6-4e66-4666-baca-a8555f0c472c",
        "listener_id": "68633f4f-f52a-402f-8572-b8173418904f",
        "default_target_group_id": "a44c4072-ed90-4b50-a33a-6b38fb10c7db",
        "tls_policy_id": "4ba79662-f2a1-41a4-a3d9-595799bbcd86"
    }
}`)

var showStagedResponse = fmt.Sprintf(`
{
    "policy": {
        "algorithm": "round-robin",
        "persistence": "cookie",
        "sorry_page_url": "https://example.com/sorry",
        "source_nat": "enable",
        "certificate_id": "f57a98fe-d63e-4048-93a0-51fe163f30d7",
        "health_monitor_id": "dd7a96d6-4e66-4666-baca-a8555f0c472c",
        "listener_id": "68633f4f-f52a-402f-8572-b8173418904f",
        "default_target_group_id": "a44c4072-ed90-4b50-a33a-6b38fb10c7db",
        "tls_policy_id": "4ba79662-f2a1-41a4-a3d9-595799bbcd86"
    }
}`)

var updateStagedRequest = fmt.Sprintf(`
{
    "policy": {
        "algorithm": "round-robin",
        "persistence": "cookie",
        "sorry_page_url": "https://example.com/sorry",
        "source_nat": "enable",
        "certificate_id": "f57a98fe-d63e-4048-93a0-51fe163f30d7",
        "health_monitor_id": "dd7a96d6-4e66-4666-baca-a8555f0c472c",
        "listener_id": "68633f4f-f52a-402f-8572-b8173418904f",
        "default_target_group_id": "a44c4072-ed90-4b50-a33a-6b38fb10c7db",
        "tls_policy_id": "4ba79662-f2a1-41a4-a3d9-595799bbcd86"
    }
}`)

var updateStagedResponse = fmt.Sprintf(`
{
    "policy": {
        "algorithm": "round-robin",
        "persistence": "cookie",
        "sorry_page_url": "https://example.com/sorry",
        "source_nat": "enable",
        "certificate_id": "f57a98fe-d63e-4048-93a0-51fe163f30d7",
        "health_monitor_id": "dd7a96d6-4e66-4666-baca-a8555f0c472c",
        "listener_id": "68633f4f-f52a-402f-8572-b8173418904f",
        "default_target_group_id": "a44c4072-ed90-4b50-a33a-6b38fb10c7db",
        "tls_policy_id": "4ba79662-f2a1-41a4-a3d9-595799bbcd86"
    }
}`)
