/*
Generated by https://github.com/tamac-io/openapi-to-eclcloud-rb
*/
package testing

import (
	"fmt"
)

const id = "497f6eca-6276-4993-bfeb-53cbbbba6f08"

var listResponse = fmt.Sprintf(`
{
    "system_updates": [
        {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "name": "security_update_202210",
            "description": "description",
            "href": "https://sdpf.ntt.com/news/2022100301/",
            "publish_datetime": "2022-10-03 00:00:00",
            "limit_datetime": "2022-10-11 12:59:59",
            "current_revision": 1,
            "next_revision": 2,
            "applicable": true
        }
    ]
}`)

var showResponse = fmt.Sprintf(`
{
    "system_update": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "security_update_202210",
        "description": "description",
        "href": "https://sdpf.ntt.com/news/2022100301/",
        "publish_datetime": "2022-10-03 00:00:00",
        "limit_datetime": "2022-10-11 12:59:59",
        "current_revision": 1,
        "next_revision": 2,
        "applicable": true
    }
}`)
