/*
Generated by https://github.com/tamac-io/openapi-to-eclcloud-rb
*/
package testing

import (
	"fmt"
)

const id = "497f6eca-6276-4993-bfeb-53cbbbba6f08"

var listResponse = fmt.Sprintf(`
{
    "listeners": [
        {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "name": "listener",
            "description": "description",
            "tags": {
                "key": "value"
            },
            "configuration_status": "ACTIVE",
            "operation_status": "COMPLETE",
            "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
            "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
            "ip_address": "10.0.0.1",
            "port": 443,
            "protocol": "https"
        }
    ]
}`)

var createRequest = fmt.Sprintf(`
{
    "listener": {
        "name": "listener",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "ip_address": "10.0.0.1",
        "port": 443,
        "protocol": "https",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040"
    }
}`)

var createResponse = fmt.Sprintf(`
{
    "listener": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "listener",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "ip_address": null,
        "port": null,
        "protocol": null
    }
}`)

var showResponse = fmt.Sprintf(`
{
    "listener": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "listener",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "ACTIVE",
        "operation_status": "COMPLETE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "ip_address": "10.0.0.1",
        "port": 443,
        "protocol": "https",
        "current": {
            "ip_address": "10.0.0.1",
            "port": 443,
            "protocol": "https"
        },
        "staged": null
    }
}`)

var updateRequest = fmt.Sprintf(`
{
    "listener": {
        "name": "listener",
        "description": "description",
        "tags": {
            "key": "value"
        }
    }
}`)

var updateResponse = fmt.Sprintf(`
{
    "listener": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "listener",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "ip_address": null,
        "port": null,
        "protocol": null
    }
}`)

var createStagedRequest = fmt.Sprintf(`
{
    "listener": {
        "ip_address": "10.0.0.1",
        "port": 443,
        "protocol": "https"
    }
}`)

var createStagedResponse = fmt.Sprintf(`
{
    "listener": {
        "ip_address": "10.0.0.1",
        "port": 443,
        "protocol": "https"
    }
}`)

var showStagedResponse = fmt.Sprintf(`
{
    "listener": {
        "ip_address": "10.0.0.1",
        "port": 443,
        "protocol": "https"
    }
}`)

var updateStagedRequest = fmt.Sprintf(`
{
    "listener": {
        "ip_address": "10.0.0.1",
        "port": 443,
        "protocol": "https"
    }
}`)

var updateStagedResponse = fmt.Sprintf(`
{
    "listener": {
        "ip_address": "10.0.0.1",
        "port": 443,
        "protocol": "https"
    }
}`)
