/*
Generated by https://github.com/tamac-io/openapi-to-eclcloud-rb
*/
package testing

import (
	"fmt"
)

const id = "497f6eca-6276-4993-bfeb-53cbbbba6f08"

var listResponse = fmt.Sprintf(`
{
    "rules": [
        {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "name": "rule",
            "description": "description",
            "tags": {
                "key": "value"
            },
            "configuration_status": "ACTIVE",
            "operation_status": "COMPLETE",
            "policy_id": "fcb520e5-858d-4f9f-bc6c-7bd225fe7cf4",
            "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
            "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
            "priority": 1,
            "target_group_id": "29527a3c-9e5d-48b7-868f-6442c7d21a95",
            "conditions": {
                "path_patterns": [
                    "^/statics/"
                ]
            }
        }
    ]
}`)

var createRequest = fmt.Sprintf(`
{
    "rule": {
        "name": "rule",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "policy_id": "fcb520e5-858d-4f9f-bc6c-7bd225fe7cf4",
        "priority": 1,
        "target_group_id": "29527a3c-9e5d-48b7-868f-6442c7d21a95",
        "conditions": {
            "path_patterns": [
                "^/statics/"
            ]
        }
    }
}`)

var createResponse = fmt.Sprintf(`
{
    "rule": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "rule",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "policy_id": "fcb520e5-858d-4f9f-bc6c-7bd225fe7cf4",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "priority": null,
        "target_group_id": null,
        "conditions": null
    }
}`)

var showResponse = fmt.Sprintf(`
{
    "rule": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "rule",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "ACTIVE",
        "operation_status": "COMPLETE",
        "policy_id": "fcb520e5-858d-4f9f-bc6c-7bd225fe7cf4",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "priority": 1,
        "target_group_id": "29527a3c-9e5d-48b7-868f-6442c7d21a95",
        "conditions": {
            "path_patterns": [
                "^/statics/"
            ]
        },
        "current": {
            "priority": 1,
            "target_group_id": "29527a3c-9e5d-48b7-868f-6442c7d21a95",
            "conditions": {
                "path_patterns": [
                    "^/statics/"
                ]
            }
        },
        "staged": null
    }
}`)

var updateRequest = fmt.Sprintf(`
{
    "rule": {
        "name": "rule",
        "description": "description",
        "tags": {
            "key": "value"
        }
    }
}`)

var updateResponse = fmt.Sprintf(`
{
    "rule": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "rule",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "policy_id": "fcb520e5-858d-4f9f-bc6c-7bd225fe7cf4",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "priority": null,
        "target_group_id": null,
        "conditions": null
    }
}`)

var createStagedRequest = fmt.Sprintf(`
{
    "rule": {
        "priority": 1,
        "target_group_id": "29527a3c-9e5d-48b7-868f-6442c7d21a95",
        "conditions": {
            "path_patterns": [
                "^/statics/"
            ]
        }
    }
}`)

var createStagedResponse = fmt.Sprintf(`
{
    "rule": {
        "priority": 1,
        "target_group_id": "29527a3c-9e5d-48b7-868f-6442c7d21a95",
        "conditions": {
            "path_patterns": [
                "^/statics/"
            ]
        }
    }
}`)

var showStagedResponse = fmt.Sprintf(`
{
    "rule": {
        "priority": 1,
        "target_group_id": "29527a3c-9e5d-48b7-868f-6442c7d21a95",
        "conditions": {
            "path_patterns": [
                "^/statics/"
            ]
        }
    }
}`)

var updateStagedRequest = fmt.Sprintf(`
{
    "rule": {
        "priority": 1,
        "target_group_id": "29527a3c-9e5d-48b7-868f-6442c7d21a95",
        "conditions": {
            "path_patterns": [
                "^/statics/"
            ]
        }
    }
}`)

var updateStagedResponse = fmt.Sprintf(`
{
    "rule": {
        "priority": 1,
        "target_group_id": "29527a3c-9e5d-48b7-868f-6442c7d21a95",
        "conditions": {
            "path_patterns": [
                "^/statics/"
            ]
        }
    }
}`)
