/*
Generated by https://github.com/tamac-io/openapi-to-eclcloud-rb
*/
package testing

import (
	"fmt"
)

const id = "497f6eca-6276-4993-bfeb-53cbbbba6f08"

var listResponse = fmt.Sprintf(`
{
    "plans": [
        {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "name": "50M_HA_4IF",
            "description": "description",
            "bandwidth": "50M",
            "redundancy": "HA",
            "max_number_of_interfaces": 4,
            "max_number_of_health_monitors": 50,
            "max_number_of_listeners": 50,
            "max_number_of_policies": 50,
            "max_number_of_routes": 25,
            "max_number_of_target_groups": 50,
            "max_number_of_members": 100,
            "max_number_of_rules": 50,
            "max_number_of_conditions": 5,
            "enabled": true
        }
    ]
}`)

var showResponse = fmt.Sprintf(`
{
    "plan": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "50M_HA_4IF",
        "description": "description",
        "bandwidth": "50M",
        "redundancy": "HA",
        "max_number_of_interfaces": 4,
        "max_number_of_health_monitors": 50,
        "max_number_of_listeners": 50,
        "max_number_of_policies": 50,
        "max_number_of_routes": 25,
        "max_number_of_target_groups": 50,
        "max_number_of_members": 100,
        "max_number_of_rules": 50,
        "max_number_of_conditions": 5,
        "enabled": true
    }
}`)
