/*
Generated by https://github.com/tamac-io/openapi-to-eclcloud-rb
*/
package testing

import (
	"fmt"
)

const id = "497f6eca-6276-4993-bfeb-53cbbbba6f08"

var listResponse = fmt.Sprintf(`
{
    "certificates": [
        {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "name": "certificate",
            "description": "description",
            "tags": {
                "key": "value"
            },
            "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
            "ca_cert": {
                "status": "NOT_UPLOADED"
            },
            "ssl_cert": {
                "status": "NOT_UPLOADED"
            },
            "ssl_key": {
                "status": "NOT_UPLOADED"
            }
        }
    ]
}`)

var createRequest = fmt.Sprintf(`
{
    "certificate": {
        "name": "certificate",
        "description": "description",
        "tags": {
            "key": "value"
        }
    }
}`)

var createResponse = fmt.Sprintf(`
{
    "certificate": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "certificate",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "ca_cert": {
            "status": "NOT_UPLOADED"
        },
        "ssl_cert": {
            "status": "NOT_UPLOADED"
        },
        "ssl_key": {
            "status": "NOT_UPLOADED"
        }
    }
}`)

var showResponse = fmt.Sprintf(`
{
    "certificate": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "certificate",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "ca_cert": {
            "status": "NOT_UPLOADED"
        },
        "ssl_cert": {
            "status": "NOT_UPLOADED"
        },
        "ssl_key": {
            "status": "NOT_UPLOADED"
        }
    }
}`)

var updateRequest = fmt.Sprintf(`
{
    "certificate": {
        "name": "certificate",
        "description": "description",
        "tags": {
            "key": "value"
        }
    }
}`)

var updateResponse = fmt.Sprintf(`
{
    "certificate": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "certificate",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "ca_cert": {
            "status": "NOT_UPLOADED"
        },
        "ssl_cert": {
            "status": "NOT_UPLOADED"
        },
        "ssl_key": {
            "status": "NOT_UPLOADED"
        }
    }
}`)

var uploadFileRequest = fmt.Sprintf(`
{
    "type": "ca-cert",
    "content": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCjAxMjM0NTY3ODlBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEKMjM0NTY3ODlBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMwo0NTY3ODlBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1CjY3ODlBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1NjcKODlBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OQpBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCCkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0QKRUZHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRgpHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdICklKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUoKS0xNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTApNTk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1OCk9QUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1OT1AKUVJTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1OT1BRUgpTVFVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1OT1BRUlNUClVWV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1OT1BRUlNUVVYKV1hZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWApZWmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaCmFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaYWIKY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MDEyMzQ1Njc4OUFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaYWJjZAplZmdoaWprbG1ub3BxcnN0dXZ3eHl6VjAxMjM0NTY3ODlBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWmFiY2RlCmZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
}`)
