/*
Generated by https://github.com/tamac-io/openapi-to-eclcloud-rb
*/
package testing

import (
	"fmt"
)

const id = "497f6eca-6276-4993-bfeb-53cbbbba6f08"

var listResponse = fmt.Sprintf(`
{
    "target_groups": [
        {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "name": "target_group",
            "description": "description",
            "tags": {
                "key": "value"
            },
            "configuration_status": "ACTIVE",
            "operation_status": "COMPLETE",
            "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
            "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
            "members": [
                {
                    "ip_address": "192.168.0.7",
                    "port": 80,
                    "weight": 1
                }
            ]
        }
    ]
}`)

var createRequest = fmt.Sprintf(`
{
    "target_group": {
        "name": "target_group",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "members": [
            {
                "ip_address": "192.168.0.7",
                "port": 80,
                "weight": 1
            }
        ]
    }
}`)

var createResponse = fmt.Sprintf(`
{
    "target_group": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "target_group",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "members": null
    }
}`)

var showResponse = fmt.Sprintf(`
{
    "target_group": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "target_group",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "ACTIVE",
        "operation_status": "COMPLETE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "members": [
            {
                "ip_address": "192.168.0.7",
                "port": 80,
                "weight": 1
            }
        ],
        "current": {
            "members": [
                {
                    "ip_address": "192.168.0.7",
                    "port": 80,
                    "weight": 1
                }
            ]
        },
        "staged": null
    }
}`)

var updateRequest = fmt.Sprintf(`
{
    "target_group": {
        "name": "target_group",
        "description": "description",
        "tags": {
            "key": "value"
        }
    }
}`)

var updateResponse = fmt.Sprintf(`
{
    "target_group": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "target_group",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "members": null
    }
}`)

var createStagedRequest = fmt.Sprintf(`
{
    "target_group": {
        "members": [
            {
                "ip_address": "192.168.0.7",
                "port": 80,
                "weight": 1
            }
        ]
    }
}`)

var createStagedResponse = fmt.Sprintf(`
{
    "target_group": {
        "members": [
            {
                "ip_address": "192.168.0.7",
                "port": 80,
                "weight": 1
            }
        ]
    }
}`)

var showStagedResponse = fmt.Sprintf(`
{
    "target_group": {
        "members": [
            {
                "ip_address": "192.168.0.7",
                "port": 80,
                "weight": 1
            }
        ]
    }
}`)

var updateStagedRequest = fmt.Sprintf(`
{
    "target_group": {
        "members": [
            {
                "ip_address": "192.168.0.7",
                "port": 80,
                "weight": 1
            }
        ]
    }
}`)

var updateStagedResponse = fmt.Sprintf(`
{
    "target_group": {
        "members": [
            {
                "ip_address": "192.168.0.7",
                "port": 80,
                "weight": 1
            }
        ]
    }
}`)
