/*
Generated by https://github.com/tamac-io/openapi-to-eclcloud-rb
*/
package testing

import (
	"fmt"
)

const id = "497f6eca-6276-4993-bfeb-53cbbbba6f08"

var listResponse = fmt.Sprintf(`
{
    "routes": [
        {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "name": "route",
            "description": "description",
            "tags": {
                "key": "value"
            },
            "configuration_status": "ACTIVE",
            "operation_status": "COMPLETE",
            "destination_cidr": "172.16.0.0/24",
            "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
            "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
            "next_hop_ip_address": "192.168.0.254"
        }
    ]
}`)

var createRequest = fmt.Sprintf(`
{
    "route": {
        "name": "route",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "destination_cidr": "172.16.0.0/24",
        "next_hop_ip_address": "192.168.0.254",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040"
    }
}`)

var createResponse = fmt.Sprintf(`
{
    "route": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "route",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "destination_cidr": "172.16.0.0/24",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "next_hop_ip_address": null
    }
}`)

var showResponse = fmt.Sprintf(`
{
    "route": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "route",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "ACTIVE",
        "operation_status": "COMPLETE",
        "destination_cidr": "172.16.0.0/24",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "next_hop_ip_address": "192.168.0.254",
        "current": {
            "next_hop_ip_address": "192.168.0.254"
        },
        "staged": null
    }
}`)

var updateRequest = fmt.Sprintf(`
{
    "route": {
        "name": "route",
        "description": "description",
        "tags": {
            "key": "value"
        }
    }
}`)

var updateResponse = fmt.Sprintf(`
{
    "route": {
        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
        "name": "route",
        "description": "description",
        "tags": {
            "key": "value"
        },
        "configuration_status": "CREATE_STAGED",
        "operation_status": "NONE",
        "destination_cidr": "172.16.0.0/24",
        "load_balancer_id": "67fea379-cff0-4191-9175-de7d6941a040",
        "tenant_id": "34f5c98ef430457ba81292637d0c6fd0",
        "next_hop_ip_address": null
    }
}`)

var createStagedRequest = fmt.Sprintf(`
{
    "route": {
        "next_hop_ip_address": "192.168.0.254"
    }
}`)

var createStagedResponse = fmt.Sprintf(`
{
    "route": {
        "next_hop_ip_address": "192.168.0.254"
    }
}`)

var showStagedResponse = fmt.Sprintf(`
{
    "route": {
        "next_hop_ip_address": "192.168.0.254"
    }
}`)

var updateStagedRequest = fmt.Sprintf(`
{
    "route": {
        "next_hop_ip_address": "192.168.0.254"
    }
}`)

var updateStagedResponse = fmt.Sprintf(`
{
    "route": {
        "next_hop_ip_address": "192.168.0.254"
    }
}`)
